<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class FrontIconFeature extends Model
{
    public $translation;
    
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::retrieved(function (FrontIconFeature $model){
            $model->translation = FrontIconFeatureTranslation::query()
                ->where('front_icon_feature_id', $model->getAttribute('id'))
                ->whereHas('language', function ($builder){
                    return $builder->where('language_code', app()->getLocale());
                })->first() ?? FrontIconFeatureTranslation::query()
                    ->first();
        });
    }

    public function translations()
    {
        return $this->hasMany(FrontIconFeatureTranslation::class);
    }
}
