<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class FrontImageFeature extends Model
{
    protected $appends = [
        'image_url'
    ];

    public $translation;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::retrieved(function (FrontImageFeature $model) {
            $model->translation = FrontImageFeatureTranslation::query()
                    ->where('front_image_feature_id', $model->getAttribute('id'))
                    ->whereHas('language', function ($builder) {
                        return $builder->where('language_code', app()->getLocale());
                    })->first() ?? FrontImageFeatureTranslation::query()
                    ->first();
        });
    }


    public function translations()
    {
        return $this->hasMany(FrontImageFeatureTranslation::class);
    }

    public function getImageUrlAttribute()
    {
        if (Str::contains($this->image, 'feature')) {
            return asset('front/assets/img/' . $this->image);
        }
        return asset_url('front-features/' . $this->image);
    }

}
